package cl.tsoft.labs.ut.sample.rest.entitie.type;

import cl.tsoft.labs.ut.sample.rest.entitie.converter.RutConverter;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvFileSource;

import static org.junit.jupiter.api.Assertions.*;

class RutTest {


// Generated by CodiumAI

        // Should return a string representation of the given Rut object
        @Test
        public void test_return_string_representation() {
            RutConverter converter = new RutConverter();
            Rut rut = new Rut(12345678, 'K');
            String result = converter.convertToDatabaseColumn(rut);
            assertEquals("12345678-K", result);
        }

        // Should return null if the given Rut object has number <= 0
        @Test
        public void test_return_null_if_number_less_than_or_equal_to_zero() {
            RutConverter converter = new RutConverter();
            Rut rut = new Rut(0, 'K');
            String result = converter.convertToDatabaseColumn(rut);
            assertNull(result);
        }

    }
